# Generated by Django 5.2.8 on 2025-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_examen_cantidad_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tiempo_limite',
            field=models.IntegerField(default=60, help_text='Tiempo total del examen en minutos'),
        ),
        migrations.AddField(
            model_name='preguntasexamen',
            name='tiempo_limite_segundos',
            field=models.IntegerField(default=60, help_text='Tiempo límite para esta pregunta en segundos'),
        ),
    ]
