# Generated by Django 5.2.8 on 2025-11-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_examen_tiempo_limite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasexamen',
            name='tiempo_limite_segundos',
        ),
        migrations.AddField(
            model_name='examen',
            name='tiempo_por_pregunta',
            field=models.FloatField(default=1.0, help_text='Tiempo por defecto por pregunta en minutos (Ej: 1.5 para 90 segundos)'),
        ),
        migrations.AddField(
            model_name='preguntasexamen',
            name='tiempo_limite_minutos',
            field=models.FloatField(blank=True, help_text='Dejar vacío para usar el tiempo por defecto del examen.', null=True),
        ),
    ]
