# Generated by Django 5.2.8 on 2025-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_preguntasexamen_tiempo_limite_segundos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='modo_cronometro',
            field=models.CharField(choices=[('MANUAL', 'Manual (Configurar Global y por Pregunta independientemente)'), ('GLOBAL_LIBRE', 'Solo Global (Libertad total para el alumno por pregunta)'), ('AUTO_DIVIDIR', 'Dividir Global (El sistema divide el tiempo global entre las preguntas)'), ('AUTO_SUMAR', 'Sumar Preguntas (El tiempo global es la suma de los tiempos de las preguntas)')], default='MANUAL', help_text='Define cómo se calculan los tiempos.', max_length=20),
        ),
    ]
