# Generated by Django 5.2.8 on 2025-11-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_examen_modo_cronometro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='modo_cronometro',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='tiempo_limite',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='tiempo_por_pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntasexamen',
            name='tiempo_limite_minutos',
        ),
    ]
