# Generated by Django 5.2.8 on 2025-11-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_examen_modo_cronometro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tiempo_limite',
            field=models.IntegerField(default=0, help_text='Tiempo total del examen en minutos'),
        ),
        migrations.AddField(
            model_name='examen',
            name='tiempo_por_pregunta',
            field=models.IntegerField(default=0, help_text='Tiempo por pregunta en segundos (0 para desactivar)'),
        ),
        migrations.AddField(
            model_name='examen',
            name='usar_tiempo_por_pregunta',
            field=models.BooleanField(default=False, help_text='Si se activa, el tiempo total se calculará automáticamente.'),
        ),
        migrations.AlterField(
            model_name='respuestasusuario',
            name='id_alternativas_examen',
            field=models.ForeignKey(blank=True, db_column='id_alternativas_examen', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.alternativasexamen'),
        ),
    ]
