# Generated by Django 5.2.8 on 2025-11-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_examen_tiempo_limite_examen_tiempo_por_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='tiempo_limite',
        ),
        migrations.AddField(
            model_name='examen',
            name='repartir_tiempo_general',
            field=models.BooleanField(default=False, help_text='Si se activa, el tiempo general se divide equitativamente entre las preguntas.'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tiempo_por_pregunta',
            field=models.IntegerField(default=0, help_text='Tiempo POR PREGUNTA en MINUTOS (solo si se activa la opción de abajo)'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='usar_tiempo_por_pregunta',
            field=models.BooleanField(default=False, help_text='Si se activa, el tiempo general se calculará automáticamente (Preguntas x Tiempo).'),
        ),
    ]
