# Generated by Django 5.2.8 on 2025-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_examen_tiempo_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tiempo_limite',
            field=models.IntegerField(default=0, help_text='Tiempo GENERAL del examen en minutos'),
        ),
    ]
