# Generated by Django 5.2.8 on 2025-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_examen_tiempo_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='repartir_tiempo_general',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='tiempo_limite',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='tiempo_por_pregunta',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='usar_tiempo_por_pregunta',
        ),
        migrations.AddField(
            model_name='examen',
            name='modo_tiempo',
            field=models.CharField(choices=[('LIBRE', 'Tiempo General Libre (Caso 1B)'), ('REPARTIDO', 'Tiempo General Repartido (Caso 1A)'), ('POR_PREGUNTA', 'Tiempo Fijo por Pregunta (Caso 2)')], default='LIBRE', help_text='Elige cómo se gestionará el tiempo del examen.', max_length=20),
        ),
        migrations.AddField(
            model_name='examen',
            name='tiempo_base_minutos',
            field=models.IntegerField(default=0, help_text='Ingrese los MINUTOS (Total o por pregunta según el modo elegido).'),
        ),
        migrations.AddField(
            model_name='examen',
            name='tiempo_limite_total_calculado',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='examen',
            name='cantidad_preguntas',
            field=models.IntegerField(default=0, help_text='0 para todas'),
        ),
    ]
