# Generated by Django 5.2.8 on 2025-11-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_examen_repartir_tiempo_general_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='tiempo_limite_total_calculado',
            new_name='tiempo_limite',
        ),
        migrations.AlterField(
            model_name='examen',
            name='modo_tiempo',
            field=models.CharField(choices=[('LIBRE', 'Caso 1B: Tiempo General Libre (Sin límite por pregunta)'), ('REPARTIDO', 'Caso 1A: Tiempo General Repartido (Se divide entre preguntas)'), ('POR_PREGUNTA', 'Caso 2: Tiempo Fijo por Pregunta (Se suma al general)')], default='LIBRE', max_length=20, verbose_name='Estrategia de Tiempo'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tiempo_base_minutos',
            field=models.IntegerField(default=0, help_text='Ingrese los MINUTOS (Total o por Pregunta según lo que elijas arriba).'),
        ),
    ]
