# Generated by Django 5.2.8 on 2025-11-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_rename_tiempo_limite_total_calculado_examen_tiempo_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasexamen',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='preguntasexamen',
            name='tipo_pregunta',
            field=models.CharField(choices=[('M', 'Opción Múltiple (Para marcar)'), ('A', 'Abierta (Para escribir/completar)')], default='M', help_text='Define si la pregunta se califica sola o requiere revisión.', max_length=1),
        ),
        migrations.AddField(
            model_name='respuestasusuario',
            name='comentario_profesor',
            field=models.TextField(blank=True, help_text='Feedback de la corrección', null=True),
        ),
        migrations.AddField(
            model_name='respuestasusuario',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntaje asignado (automático o manual)', max_digits=4),
        ),
        migrations.AddField(
            model_name='respuestasusuario',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Lo que escribió el alumno', null=True),
        ),
    ]
