# Generated by Django 5.2.8 on 2025-11-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_preguntasexamen_puntaje_maximo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasexamen',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='preguntasexamen',
            name='tipo_pregunta',
            field=models.CharField(choices=[('M', 'Opción Múltiple (Automática)'), ('A', 'Abierta / Texto (Manual)')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='respuestasusuario',
            name='comentario_profesor',
            field=models.TextField(blank=True, help_text='Feedback', null=True),
        ),
        migrations.AlterField(
            model_name='respuestasusuario',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntaje ganado en esta pregunta (auto o manual)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='respuestasusuario',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Respuesta escrita por el alumno', null=True),
        ),
    ]
