# Generated by Django 5.2.8 on 2025-12-03 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_preguntasexamen_puntaje_maximo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Usuario no detectado en cámara'), ('MULTIPLE', 'Múltiples personas detectadas'), ('SUPLANTACION', 'Rostro no coincide con el perfil'), ('CELULAR', 'Uso de celular detectado')], max_length=20)),
                ('minuto_ocurrencia', models.CharField(help_text='Ej: 10:45', max_length=10)),
                ('evidencia', models.ImageField(blank=True, help_text='Captura del momento', null=True, upload_to='biometria/incidentes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.examen')),
            ],
            options={
                'db_table': 'incidencias_examen',
            },
        ),
        migrations.CreateModel(
            name='PerfilBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_referencia', models.ImageField(help_text='Foto oficial para comparar', upload_to='biometria/referencias/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
